### ISSUE TITLE
Pixel 3 设置壁纸奔溃【bug】

### ISSUE THREAD

**Issue by akFace** [SherlockGougou/WallpaperDemo#1]
### 报错信息如图：
![image](https://user-images.githubusercontent.com/22288837/57693588-29c04700-767c-11e9-8d68-2600732052b6.png)

### 高于Android7.1.1崩溃，
![image](https://user-images.githubusercontent.com/22288837/57693599-30e75500-767c-11e9-96a3-edae3fa396f2.png)

**Comment by SherlockGougou** [comment]
看报错日志是 N 的文件权限导致的，你排查一下是否是未配置author

**Comment by akFace** [comment]
#### 小米、华为都成功了，原生ROM的不行
#### 已经配置了的，如图:innocent:：

![image](https://user-images.githubusercontent.com/22288837/57694127-83754100-767d-11e9-829c-91543ad865cd.png)
#### 调用：
![image](https://user-images.githubusercontent.com/22288837/57694154-8f610300-767d-11e9-9f9c-7f8b9a307ba9.png)

**Comment by SherlockGougou** [comment]
这里改成这样试试：
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                try {
                    intent =
                        WallpaperManager.getInstance(context.getApplicationContext()).getCropAndSetWallpaperIntent(uriPath);
                    intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                    context.getApplicationContext().startActivity(intent);
                } catch (IllegalArgumentException e) {
                    Bitmap bitmap = null;
                    try {
                        bitmap = MediaStore.Images.Media.getBitmap(context.getApplicationContext().getContentResolver(), uriPath);
                        if (bitmap != null) {
                            WallpaperManager.getInstance(context.getApplicationContext()).setBitmap(bitmap);
                        }
                    } catch (IOException e1) {
                        e1.printStackTrace();
                    }
                }
            }
```

**Comment by SherlockGougou** [comment]
已发布v1.3.0，更改依赖试试。

**Comment by akFace** [comment]
> 已发布v1.3.0，更改依赖试试。

设置壁纸成功了，不崩溃了 :smiley:

**Comment by akFace** [comment]
> > 已发布v1.3.0，更改依赖试试。
> 
> 多谢哈！ 设置壁纸成功了，不崩溃了 😃

**Comment by akFace** [comment]
> > > 已发布v1.3.0，更改依赖试试。
> > 
> > 
> > 多谢哈！ 设置壁纸成功了，不崩溃了 😃

没有回调，不知道设置是否成功 :joy:

**Comment by akFace** [comment]
#### 能否加个回调呀

**Comment by SherlockGougou** [comment]
最近不是很闲，等闲下来搞。你也可以自己搞搞。

**Comment by akFace** [comment]
> 最近不是很闲，等闲下来搞。你也可以自己搞搞。

嗯嗯，等你的 v1.4.0 😂
